language: ruby

matrix:
  include:
  - rvm: ruby-head
    gemfile: Gemfile
  - rvm: 2.6
    gemfile: gemfiles/rails6.1.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails5.2.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails4.2.gemfile
  - rvm: 2.2
    gemfile: gemfiles/rails3.2.gemfile

script: bundle exec rspec spec
